name: fib
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest  
    steps:
     - name: sum
       shell: bash
       run: |
        prev_fib=${{ secrets.PREV_FIB_NUM }}
        curr_fib=${{ secrets.CURR_FIB_NUM }}
        next_fib=$((${prev_fib:-0} + ${curr_fib:-1}))
        echo "prev=$curr_fib" >> $GITHUB_ENV
        echo "curr=$next_fib" >> $GITHUB_ENV
     - uses: gliech/create-github-secret-action@v1
       with:
         name: PREV_FIB_NUM
         value: ${{ env.prev }}
         pa_token: ${{ secrets.PA_TOKEN }}
     - uses: gliech/create-github-secret-action@v1
       with:
         name: CURR_FIB_NUM
         value: ${{ env.curr }}
         pa_token: ${{ secrets.PA_TOKEN }}
     - name: Create commit comment
       uses: peter-evans/commit-comment@v2
       with:
          body: |
            Your Fibonacci number is ${{ env.curr }}.
